In [1]:
import numpy as np

In [22]:
x = np.array([[1,0],[1,1],[1,2]])
x

array([[1, 0],
       [1, 1],
       [1, 2]])

In [23]:
xt = x.transpose()
xt

array([[1, 1, 1],
       [0, 1, 2]])

In [29]:
y = np.array([[1],[3],[2]])
y

array([[1],
       [3],
       [2]])

In [30]:
xtx = np.matmul(xt,x)
xtx

array([[3, 3],
       [3, 5]])

In [39]:
ixtx = np.linalg.inv(xtx)
ixtx

array([[ 0.83333333, -0.5       ],
       [-0.5       ,  0.5       ]])

In [40]:
xty = np.matmul(xt,y)
xty

array([[6],
       [7]])

In [41]:
b = np.matmul(ixtx, xty)
b

array([[1.5],
       [0.5]])